export const productSeed = [
  {
    slug: 'founder-pack',
    name: 'Founder Pack',
    description: 'Account-level founder entitlement with beta access and cosmetic flags.',
    entitlementKey: 'founder_pack',
    stripePriceId: 'price_founder_pack_test',
    unitAmount: 2999,
    currency: 'usd',
    isVisible: true,
    isActive: true,
    seoTitle: 'Founder Pack - Resurgence',
    seoDescription: 'Reserve account-level founder access for Resurgence.',
  },
  {
    slug: 'base-game-access',
    name: 'Base Game Access',
    description: 'Account-level access entitlement for the base game.',
    entitlementKey: 'base_game_access',
    stripePriceId: 'price_base_game_access_test',
    unitAmount: 1999,
    currency: 'usd',
    isVisible: true,
    isActive: true,
    seoTitle: 'Base Game Access - Resurgence',
    seoDescription: 'Begin your account journey in Resurgence.',
  },
  {
    slug: 'internal-test-product',
    name: 'Internal Test Product',
    description: 'Hidden product used for staging setup.',
    entitlementKey: 'internal_test',
    stripePriceId: 'price_internal_test',
    unitAmount: 1,
    currency: 'usd',
    isVisible: false,
    isActive: false,
    seoTitle: 'Hidden',
    seoDescription: 'Hidden',
  },
] as const;
